table _Measures
	lineageTag: ffe9f67c-e5fe-471c-af2f-89da4e3646de

	measure 'Units YTD' = ```
			
			    TOTALYTD ( [Units], DimDate[Date] )
			```
		formatString: 0
		lineageTag: 1d8be16d-6058-4522-ba76-62726a732c11

	measure Units = ```
			
			    SUM ( FactSales[Quantity] )
			```
		formatString: 0
		lineageTag: 1794a6e6-de18-40dd-ae1f-511735eeb8f1

	measure 'Tax Amount' = ```
			
			    SUM ( FactSales[TaxAmount] )
			```
		lineageTag: 49f5d521-c494-41db-8af6-6ce39b37a63a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YTD Rank (Product)' = ```
			
			    RANKX (
			        ALLSELECTED ( DimProduct[ProductName] ),
			        [Revenue YTD],
			        ,
			        DESC,
			        DENSE
			    )
			```
		formatString: 0
		lineageTag: 923d8d9b-1e53-43d2-8134-b6198cfc1f34

	measure 'Revenue YTD Rank (Customer)' = ```
			
			    RANKX (
			        ALLSELECTED ( DimCustomer[CustomerName] ),
			        [Revenue YTD],
			        ,
			        DESC,
			        DENSE
			    )
			```
		formatString: 0
		lineageTag: b9bb9988-c553-4146-aebc-283c4cd5e2ef

	measure 'Revenue YTD' = ```
			
			    TOTALYTD ( [Revenue], DimDate[Date] )
			```
		lineageTag: db21e8bc-b286-4e02-bf9a-7009c6e0d02f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YoY Δ' = ```
			
			    [Revenue] - [Revenue LY]
			```
		lineageTag: 8840b937-9a16-4d48-ab8f-c96daa72348f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YoY %' = ```
			
			    DIVIDE ( [Revenue YoY Δ], [Revenue LY] )
			```
		lineageTag: a7b1a414-e962-4155-9e49-1b8c8dec53db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var vs Target YTD' = ```
			
			    [Revenue YTD] - [Target YTD]
			```
		lineageTag: 79623198-4ad3-4884-9893-567cfc710972

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var vs Target QTD' = ```
			
			    [Revenue QTD] - [Target QTD]
			```
		lineageTag: 66a0dcef-fbbf-48c9-8083-7cb353661e6d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var vs Target MTD' = ```
			
			    [Revenue MTD] - [Target MTD]
			```
		lineageTag: 7eda1bac-020e-48c5-aae3-ebe80423bb69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var vs Target' = ```
			
			    [Revenue] - FactTargets[Target]
			```
		lineageTag: 096b1fd8-18c3-4609-b5fa-eccd61578390

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var % vs Target YTD' = ```
			
			    DIVIDE ( [Revenue Var vs Target YTD], [Target YTD] )
			```
		lineageTag: 89475ca4-f3af-445e-a1c6-fe74df3eefcb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var % vs Target QTD' = ```
			
			    DIVIDE ( [Revenue Var vs Target QTD], [Target QTD] )
			```
		lineageTag: c1f3f8ee-e2c2-4a7b-be13-e38970454379

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var % vs Target MTD' = ```
			
			    DIVIDE ( [Revenue Var vs Target MTD], [Target MTD] )
			```
		lineageTag: c101a9d6-e4bc-4d79-8026-12792d8f7d89

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Var % vs Target' = ```
			
			    DIVIDE ( [Revenue Var vs Target], FactTargets[Target] )
			```
		lineageTag: 6941ab80-e776-4aae-b964-e1c17b606cb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue QTD' = ```
			
			    TOTALQTD ( [Revenue], DimDate[Date] )
			```
		lineageTag: 0051d37f-7d05-490e-9ca1-e7e91ecdff76

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue PM' = ```
			
			    CALCULATE ( [Revenue], PARALLELPERIOD ( DimDate[Date], -1, MONTH ) )
			```
		lineageTag: 7143aaa3-cd04-477d-81e8-6626c5f2d318

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue MTD' = ```
			
			    TOTALMTD ( [Revenue], DimDate[Date] )
			```
		lineageTag: ab91cd9a-f2c8-4615-8367-0e91477262ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue MoM Δ' = ```
			
			    [Revenue] - [Revenue PM]
			```
		lineageTag: 4cedf59e-62e5-4052-868e-d3b3267b580f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue MoM %' = ```
			
			    DIVIDE ( [Revenue MoM Δ], [Revenue PM] )
			```
		lineageTag: 6705d4ef-f5c4-4f00-88ca-caa14235dab5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue LY' = ```
			
			    CALCULATE ( [Revenue], DATEADD ( DimDate[Date], -1, YEAR ) )
			```
		lineageTag: 2bcd35cf-51eb-44c1-b568-40a4ab51bbd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue LTM YoY %' = ```
			
			    DIVIDE ( [Revenue LTM] - [Revenue LTM LY], [Revenue LTM LY] )
			```
		lineageTag: 53b7c95e-1bb9-4827-bbbf-3e8251bddc23

	measure 'Revenue LTM' = ```
			
			    CALCULATE (
			        [Revenue],
			        DATESINPERIOD ( DimDate[Date], MAX ( DimDate[Date] ), -12, MONTH )
			    )
			```
		lineageTag: 9515515a-4886-4465-a7f3-9049cda9614c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Revenue = ```
			
			    SUM ( FactSales[SalesAmount] )
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 633e41bd-73ad-4d95-94fc-1dc0f307c28b

	measure 'Gross Profit YTD' = ```
			
			    TOTALYTD ( [Gross Profit], DimDate[Date] )
			```
		lineageTag: 058ba47f-09ac-408d-a221-03e77c5927af

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit YoY %' = ```
			
			    DIVIDE ( [Gross Profit] - [Gross Profit LY], [Gross Profit LY] )
			```
		lineageTag: 9ac34947-70ab-42cc-8f0e-b5984ba46b4d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit MTD' = ```
			
			    TOTALMTD ( [Gross Profit], DimDate[Date] )
			```
		lineageTag: 6509c65f-9490-44dc-bcf9-4a2350553047

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit LY' = ```
			
			    CALCULATE ( [Gross Profit], DATEADD ( DimDate[Date], -1, YEAR ) )
			```
		lineageTag: 9c091c36-018b-4751-afb6-62ee5c09d535

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit' = ```
			
			    [Revenue] - [COGS]
			```
		lineageTag: bd214fa6-fa59-4805-af33-fc04046592e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Margin % YTD' = ```
			
			    DIVIDE ( [Gross Profit YTD], [Revenue YTD] )
			```
		lineageTag: fade0d8d-44fe-4742-a05f-21df6d64f879

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Margin % MTD' = ```
			
			    DIVIDE ( [Gross Profit MTD], [Revenue MTD] )
			```
		lineageTag: af31bce9-06a7-45fb-8b63-41656fd6bf08

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Margin %' = ```
			
			    DIVIDE ( [Gross Profit], [Revenue] )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e44c67b2-3130-489b-9dc8-8be58869a40b

	measure 'Discount Amount' = ```
			
			    SUM ( FactSales[DiscountAmount] )
			```
		lineageTag: 82e77370-7f59-401b-a051-1a326beba580

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Discount %' = ```
			
			    DIVIDE ( [Discount Amount], [Revenue] )
			```
		lineageTag: 0b34fe4b-6bf0-4ed2-ae7c-372dbd60d5ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS = ```
			
			    SUM ( FactSales[CostAmount] )
			```
		lineageTag: 3cd39632-f7f5-4052-a7f7-207e6bb59c9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ASP YTD' = ```
			
			    DIVIDE ( [Revenue YTD], [Units YTD] )
			```
		lineageTag: 6510f5df-51ab-4605-be04-5c303ce153fd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ASP = ```
			
			    DIVIDE ( [Revenue], [Units] )
			```
		lineageTag: 17bf076d-2ff9-4414-b876-74259812e350

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MaxY = ```
			
			    MAX([Revenue])* 1.5
			```
		lineageTag: 382377f9-8623-4324-b8cc-3286e47a4829

	measure 'CR MEMO' = DIVIDE(COUNTROWS(FactSales) , 1.34)
		lineageTag: b556f056-b0fc-493d-b475-f2b2d2c21808

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue CY vs Revenue LY %' =
			
			VAR Result = DIVIDE ( [Revenue] - [Revenue LY], [Revenue LY] )
			RETURN
			    IF (
			        Result > 0,
			        "▲ " & FORMAT ( Result, "0.0%" ),
			        IF (
			            Result < 0,
			            "▼ " & FORMAT ( Result, "0.0%" ),
			            FORMAT ( Result, "0.0%" )
			        )
			    )
		lineageTag: 605c3518-3178-4b84-ac96-c0beff2b7e5b

	measure 'Units LY' = ```
			
			    CALCULATE ( [Units], DATEADD ( DimDate[Date], -1, YEAR ) )
			```
		formatString: 0
		lineageTag: 023e313a-5422-4e13-becc-22791e9bf32b

	measure 'Units CY vs Units LY %' =
			
			VAR Result = DIVIDE ( [Units] - [Units LY], [Units LY] )
			RETURN
			    IF (
			        Result > 0,
			        "▲ " & FORMAT ( Result, "0.0%" ),
			        IF (
			            Result < 0,
			            "▼ " & FORMAT ( Result, "0.0%" ),
			            FORMAT ( Result, "0.0%" )
			        )
			    )
		lineageTag: 697be4da-6561-4bbc-b531-f0b5f6a390be

	column Column1
		dataType: string
		lineageTag: 7dc9ef9d-2710-48ca-a569-e0470d53058d
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

